version: "2"

services:
  tv7:
    build: /srv/docker/git/tv7
    container_name: tv7
    volumes:
      - tv7_config:/config
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost/api/status
      interval: 90s
      timeout: 10s
      retries: 10
      start_period: 60s

